{{- $conf := list
    (include "armonik.conf.control" $ | fromYaml)
    (include "armonik.control.confHelper" $ | fromYaml)
    .Values.conf
  | include "armonik.conf.merge" | fromYaml -}}
{{- $image := list $ .Values.image | include "armonik.image" | fromYaml }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "armonik.fullname" . }}
  namespace: {{ include "armonik.namespace" . }}
  labels:
    app.kubernetes.io/component: control-plane
    {{- include "armonik.labels" . | nindent 4 }}
  {{- with .Values.annotations}}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: control-plane
      {{- include "armonik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: control-plane
        {{- include "armonik.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: control-plane
          image: {{ $image.fullname }}
          imagePullPolicy: {{ $image.pullPolicy }}
          #command: ["/bin/bash", "-c", "sleep 3600"]
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}{{/* range .Values.ports */}}
          env: {{- include "armonik.conf.generateEnv" $conf | nindent 12 }}
          envFrom: {{- include "armonik.conf.generateEnvFrom" $conf | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{/* with .Values.resources */}}
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}{{/* with .Values.livenessProbe */}}
          {{- with .Values.startupProbe }}
          startupProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}{{/* with .Values.startupProbe */}}
          volumeMounts: {{- include "armonik.conf.generateVolumeMounts" $conf | nindent 12 }}
      volumes: {{- include "armonik.conf.generateVolumes" $conf | nindent 8 }}
      {{- with .Values.global.imagePullSecrets | default .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{/* with $imagePullSecrets */}}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "armonik.serviceAccountName" $ }}
      serviceAccount: {{ include "armonik.serviceAccountName" $ }}
      automountServiceAccountToken: true
      {{- end }}{{/* if .Values.serviceAccount.create */}}
      shareProcessNamespace: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{/* with .Values.nodeSelector */}}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{/* with .Values.tolerations */}}
      enableServiceLinks: true
