{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "armonik.serviceAccountName" . }}
  namespace: {{ include "armonik.namespace" . }}
  labels:
    app.kubernetes.io/component: control-plane
    {{- include "armonik.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.secrets }}
secrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
