{{- $image := list $ .Values.image | include "armonik.image" | fromYaml }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "armonik.fullname" . }}
  namespace: {{ include "armonik.namespace" . }}
  labels:
    app.kubernetes.io/component: ingress
    {{- include "armonik.labels" . | nindent 4 }}
  {{- with .Values.annotations}}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: ingress
      {{- include "armonik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ingress
        {{- include "armonik.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: true
      containers:
      - name: ingress
        image: {{ $image.fullname }}
        imagePullPolicy: {{ $image.pullPolicy }}
        ports:
          {{- range .Values.ports }}
          - name: {{ .name }}
            containerPort: {{ .containerPort }}
            protocol: TCP
          {{- end }}{{/* range .Values.ports */}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}{{/* with .Values.resources */}}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}{{/* with .Values.livenessProbe */}}
        {{- with .Values.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}{{/* with .Values.startupProbe */}}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}{{/* with .Values.readinessProbe */}}
        {{- with .extraEnv }}
        env:
          {{- .extraEnv | toYaml | nindent 10 }}
        {{- end }}
        {{- with .extraEnvFrom }}
        envFrom:
          {{- .extraEnvFrom | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if list .Values "tls" "enabled" | include "armonik.index" }}
        - name: server-cert
          mountPath: /ingress
          mountPropagation: None
          readOnly: true
        {{- end }}
        {{- if list .Values "mtls" "enabled" | include "armonik.index" }}
        - name: client-cert
          mountPath: /ingressclient
          mountPropagation: None
          readOnly: true
        {{- end }}
        - mountPath: /etc/nginx/conf.d
          mountPropagation: None
          name: conf
          readOnly: true
        - mountPath: /static
          mountPropagation: None
          name: static
          readOnly: true
        {{- with .extraVolumeMounts }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      shareProcessNamespace: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{/* with .Values.nodeSelector */}}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{/* with .Values.tolerations */}}
      enableServiceLinks: true
      volumes:
      {{- if list .Values "tls" "enabled" | include "armonik.index" }}
      - name: server-cert
        secret:
          defaultMode: 420
          optional: false
          secretName: {{ include "armonik.fullname" . }}-cert
      {{- end }}
      {{- if list .Values "mtls" "enabled" | include "armonik.index" }}
      - name: client-cert
        secret:
          defaultMode: 420
          optional: false
          secretName: {{ include "armonik.fullname" . }}-cert
      {{- end}}
      - name: conf
        configMap:
          name: {{ include "armonik.fullname" . }}-conf
          defaultMode: 420
          optional: false
      - name: static
        configMap:
          name: {{ include "armonik.fullname" . }}-static
          defaultMode: 420
          optional: false
      {{- with .extraVolumeMounts }}
      {{ . | toYaml | nindent 6 }}
      {{- end }}
