apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "armonik.ingress.fullname" . }}-gui
    service: admin-gui
  name: admin-gui
spec:
  ports:
  - port: {{ .Values.adminGui.port }}
    targetPort: 1080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
    service: admin-gui
