imagePullSecrets: []
replicaCount: 1
namespace: armonik
name: control-plane
image:
  repository: dockerhubaneo
  name: armonik_control
  tag: "0.35.0"
  pullPolicy: IfNotPresent
imageJob:
  repository: alpine
  name: mongosh
  tag: "2.0.2"
imageCron:
  repository: datalust
  name: seqcli
  tag: "2024.3"

serviceAccount:
  create: true
  name: control-plane
  annotations: {}
  secrets: []

certificates:
  enable: false
partitionMetricsExporter:
  enable: false
metricsExporter:
  enable: true

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /liveness
    port: 1081
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 1

startupProbe:
  httpGet:
    path: /startup
    port: 1081
  initialDelaySeconds: 15
  periodSeconds: 3
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 20

nodeSelector: {}

tolerations: []

annotations: {}

conf:
  env: {}
  envConfigmap: []
  envFromConfigmap: {}
  envSecret: []
  envFromSecret: {}
  mountConfigmap: {}
  mountSecret: {}

volumes:
  # activemq:
  #   enabled: true
  #   mountPath: /amqp
  #   secretName: activemq-crt
  # mongodb:
  #   enabled: true
  #   mountPath: /mongodb/certs/
  #   secretName: mongodb-ca
  # redis:
  #   enabled: true
  #   mountPath: /redis
  #   secretName: redis-crt

env:
  - name: MongoDB__Password
    valueFrom:
      secretKeyRef:
        key: mongodb-root-password
        name: mongodb
  - name: Redis__Password
    valueFrom:
      secretKeyRef:
        key: redis-password
        name: redis

envFrom:
  secretRef:
    - redis
  configMapRef:
    - control-plane-configmap
    - core-configmap
    - log-configmap

ports:
  - name: control-port
    containerPort: 1080
    protocol: TCP
  - name: metrics-port
    containerPort: 1081
    protocol: TCP

config:
  controlPlane:
    name: control-plane-configmap
    defaultPartition: default
    data:
      Submitter__MaxErrorAllowed: "50"

  computePlane:
    partitions:
      default: {}
      stream: {}
      htcmock: {}
      bench: {}

service:
  name: control-plane
  serviceType: ClusterIP

  ports:
    - name: control-port
      port: 5001
      targetPort: 1080

  selector:
    app: armonik
    service: control-plane
