nameOverride: ""
imagePullSecrets: []
image:
  registry:
  repository: nginxinc
  name: nginx-unprivileged
  tag: 1.27.4-alpine-slim
  pullPolicy: IfNotPresent

replicas: 1

nodeSelector: {}
tolerations: []
annotations: {}
affinity: {}

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

ports:
  - name: ingress-grpc
    containerPort: 9080
    servicePort: 5001
    http2: true
  - name: ingress-http
    containerPort: 8080
    servicePort: 5000

service:
  type: LoadBalancer
  annotations:

tls:
  clusterDomain: cluster.local
  certManager:
    addInjectorAnnotations: true
    existingIssuer:
      # Use an existing cert-manager issuer
      enabled: false
      # Kind of the existing cert-manager issuer
      kind: "Issuer"
      # Name of the existing cert-manager issuer
      name: "my-issuer"
    # Set the requested duration (i.e. lifetime) of the Certificate.
    # See https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
    duration: ""
    # How long before the currently issued certificateâ€™s expiry cert-manager should renew the certificate.
    # See https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
    renewBefore: ""
    # Add extra annotations to the Certificate resource
    annotations: {}
    # Add extra labels to the Certificate resource
    labels: {}

volumes:
  #ingressSecret: ingress-crt
  mongodbSecret: mongodb
  #mongodbSecretCrt: mongodb-ca
  nginxConfigMap: armonik-ingress-conf
  nginxStaticConfigMap: armonik-ingress-static

###########################################################
# Admin GUI
###########################################################
gui:
  image:
    registry:
    repository: dockerhubaneo
    name: armonik_admin_app
    tag:
    pullPolicy: IfNotPresent
  ports:
    - name: gui
      containerPort: 1080
      servicePort: 1080
  service:
    type: ClusterIP
    annotations:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector:
  tolerations:
  annotations:
  affinity:

static:
  environment.json:
    color: "#80ff80"
    description: "{{ .Values.global.environment.description }}"
    name: "{{ .Values.global.environment.name }}"
    version: "{{ .Chart.AppVersion }}"
  gui_configuration: {}
