{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: {{ include "armonik.compute.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "armonik.compute.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armonik.compute.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "armonik.compute.selectorLabels" . | nindent 6 }}
{{- end -}}
